
--
-- PostgreSQL database dump
-- Inspired from https://fr.wikipedia.org/wiki/Projet:Math%C3%A9matiques/Liste_des_math%C3%A9maticiens
--

\set AUTOCOMMIT off
\set ON_ERROR_ROLLBACK on

SET client_encoding = 'UTF8';

DROP TABLE public.mathematicians;
CREATE TABLE public.mathematicians (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname varchar(255) NOT NULL,
  lastname varchar(255),
  country varchar(255),
  birth smallint,
  death smallint
);

COPY public.mathematicians (firstname, lastname, country, birth, death) FROM stdin;
Colin	Maclaurin	Écosse	1698	1746
János	Bolyai	Hongrie	1802	1860
Ghiyath	al-Kashi	Perse	1370	1430
Nicholas	Metropolis	États-Unis	1915	1999
George	Dantzig	États-Unis	1914	2005
Simon	Newcomb	États-Unis	1835	1909
Nathan	Jacobson	Pologne	1910	1999
Leonardo Torres	Quevedo	Espagne	1852	1936
Ludolph van	Ceulen	Allemagne	1540	1610
Piergiorgio	Odifreddi	Italie	1950	\N
Yutaka	Taniyama	Japon	1927	1958
Viggo	Brun	Norvège	1885	1978
Varahamihira	\N	Inde	505	587
Roger	Cotes	Angleterre	1682	1716
Johannes	Kepler	Allemagne	1571	1630
Rudolf	Lipschitz	Allemagne	1832	1903
Ernst Friedrich Ferdinand	Zermelo	Allemagne	1871	1953
Tadeusz	Ważewski	Pologne	1896	1972
Stanisław	Zaremba	Pologne	1863	1942
Jørgen Pedersen	Gram	Danemark	1850	1916
Frank	Morley	Angleterre	1860	1937
Alexandre de	Villedieu	France	1200	1250
Michael Francis	Atiyah	Angleterre	1929	\N
Jacques	Bernoulli	Suisse	1654	1705
Felix	Hausdorff	Allemagne	1869	1942
Eduard	Heine	Allemagne	1821	1881
Abu al Hassan Thabit ibn	Qurra	Turquie-Irak	826	901
Gábor	Szegö	Hongrie	1895	1985
Charles Émile	Picard	France	1856	1941
Jost	Bürgi	Suisse	1552	1632
Pierre de	Fermat	France	1601	1665
Edward	Waring	Angleterre	1736	1798
Johann Benedict	Listing	Allemagne	1808	1882
Marie	Crous	France	1600	1700
Théétète	d'Athènes	Grèce	-415	-369
Philippe de La	Hire	France	1640	1718
Sarvadaman	Chowla	Inde	1907	1995
Gaspard	Monge	France	1746	1818
Herbert Samuel	Zuckerman	États-Unis	1912	1970
Wilhelm	Ackermann	Allemagne	1896	1962
Mark	Kac	Pologne	1914	1984
Antiphon le	Sophiste	Grèce	-500	-450
Wendelin	Werner	France	1968	\N
Samuel	Eilenberg	Pologne	1913	1998
Joseph	Liouville	France	1809	1882
Fan	Chung	Taïwan	1949	\N
Paul-André	Meyer	France	1934	2003
Dinostrate	\N	Grèce	-450	-400
Yuri	Linnik	Russie	1915	1972
Jean Baptiste Joseph	Fourier	France	1768	1830
Jesse	Douglas	États-Unis	1897	1967
Alexandre	Alexandrov	Russie	1912	1999
Leopold	Löwenheim	Allemagne	1878	1957
Johann Heinrich	Rahn	Suisse	1622	1676
Lev	Pontryagin	Russie	1908	1988
Waclaw	Sierpinski	Pologne	1882	1969
Stanislaw	Lesniewski	Pologne	1886	1939
Charles de	Bovelles	France	1475	1566
Alan	Turing	Angleterre	1912	1954
Lars	Hörmander	Suède	1931	2012
Paul	Bachmann	Allemagne	1837	1920
Chiungtze	Tsen	Chine	1898	1940
Alexandre	Grothendieck	France	1928	2014
Theodor	Molien	Russie	1861	1941
Jean de	Beaugrand	France	1584	1640
Guillaume François Antoine, marquis de	L'Hôpital	France	1661	1704
Godfrey Harold	Hardy	Angleterre	1877	1947
Nicole El	Karoui	France	1944	\N
Tullio	Levi-Civita	Italie	1873	1941
Cesare	Burali-Forti	Italie	1861	1931
Emanuel	Sperner	Allemagne	1905	1980
Otto	Hölder	Allemagne	1859	1937
August Ferdinand	Möbius	Allemagne	1790	1868
Dirk Jan	Struik	Hollande	1894	2000
Gerhard	Gentzen	Allemagne	1909	1945
Hilda Geiringer von	Mises	Allemagne	1893	1973
Nicolas	d'Oresme	France	1323	1382
Machgielis	Euwe	Hollande	1901	1981
Jules	Richard	France	1862	1956
Yoriyuki	Arima	Japon	1714	1783
Henry	Briggs	Angleterre	1561	1630
Âryabhata	\N	Inde	400	500
Giusto	Bellavitis	Italie	1803	1880
David van	Dantzig	Hollande	1900	1959
Karl	Menger	Autriche	1902	1985
Jérôme	Cardan	Italie	1501	1576
Leonard	Carlitz	États-Unis	1907	1999
Thomas	Bayes	Angleterre	1702	1761
Solomon	Golomb	États-Unis	1930	2016
August Leopold	Crelle	Allemagne	1780	1855
Derrick Henry	Lehmer	États-Unis	1905	1991
John	Milnor	États-Unis	1931	\N
Grace Chisholm	Young	Royaume-Uni	1868	1944
Benjamin	Peirce	États-Unis	1809	1880
Chidambaram Padmanabhan	Ramanujam	Inde	1938	1974
Jacques Pelletier du	Mans	France	1517	1582
Johann Heinrich	Lambert	Allemagne	1728	1777
Ivan	Niven	Canada	1915	1999
Luigi	Bianchi	Italie	1856	1928
Théodore de	Cyrène	Grèce	-470	-420
Ferdinand von	Lindemann	Allemagne	1852	1939
Robert	Fano	Italie	1917	2016
Enrico	Bombieri	Italie	1940	\N
Nikolai	Luzin	Russie	1883	1950
John Charles	Fields	Canada	1863	1932
Siméon Denis	Poisson	France	1781	1840
Alexis Claude	Clairaut	France	1713	1765
Cahit	Arf	Turquie	1910	1997
Mary	Cartwright	Angleterre	1900	1998
Kurt	Gödel	Autriche	1906	1978
Georg von	Purbach	Autriche	1423	1461
Martin	Davis	États-Unis	1928	\N
Satyendranath	Bose	Inde	1894	1974
Albert	Einstein	Allemagne	1879	1955
Nicolas	Chuquet	France	1445	1500
Solomon	Lefschetz	États-Unis	1884	1972
Lipót	Fejér	Hongrie	1880	1959
Jacques	Hadamard	France	1865	1963
Emanuel	Lasker	Allemagne	1868	1941
Johannes Campanus de	Novare	Italie	1220	1296
Nicolas de	Cuse	Allemagne	1401	1464
Abraham de	Moivre	France	1667	1754
Marie-Charlotte	de Romilley de La Chesnelaye	France	\N	1737
Ferdinand	Eisenstein	Allemagne	1823	1852
Jean-Victor	Poncelet	France	1788	1867
Giulio	Ascoli	Italie	1843	1896
Boris Yakovlevich	Bukreev	Russie	1859	1962
Kurt	Hensel	Allemagne	1861	1941
Efim	Zelmanov	Russie	1955	\N
Alexandre-Théophile	Vandermonde	France	1735	1796
Albrecht	Dürer	Allemagne	1471	1528
Jean Alexandre	Dieudonné	France	1906	1992
Jürgen K.	Moser	Allemagne	1928	1999
Nicomaque de	Gerasa	Grèce	200	\N
Edward	Witten	États-Unis	1951	\N
Ptolémée	\N	Égypte	90	168
Marian	Rejewski	Pologne	1905	1980
Pierre-Simon de	Laplace	France	1749	1827
Michael	Freedman	États-Unis	1951	\N
Christophorus	Clavius	Allemagne	1537	1612
Christian	Kramp	France	1760	1826
Paolo	Ruffini	Italie	1765	1822
René	Descartes	France	1596	1650
Leopold	Vietoris	Autriche	1891	2002
Victor Alexandre	Puiseux	France	1820	1883
Jean-Robert	Argand	Suisse	1768	1822
Gregory J.	Chaitin	États-Unis	1947	\N
Évariste	Galois	France	1811	1832
Apollonius de	Perga	Grèce	-262	-180
André	Weil	France	1906	1998
Joseph	Wolstenholme	Angleterre	1829	1891
Pierre	Varignon	France	1654	1722
Eberhard	Hopf	Autriche	1902	1983
Jacopo	Riccati	Italie	1676	1754
Gaspard Lax de	Sarenina	Espagne	1487	1560
Grégoire de	Saint-Vincent	Belgique	1584	1667
Seki	Kowa	Japon	1642	1708
Leonhard	Euler	Suisse	1707	1783
Peter Ludwig Mejdell	Sylow	Norvège	1832	1918
Václav	Hlavatý	République tchèque	1894	1969
Hippocrate de	Chios	Grèce	-475	-425
Michel	Rolle	France	1652	1719
Hermann	Minkowski	Allemagne	1864	1909
Emmy	Noether	Allemagne	1882	1935
Joseph Louis Francois	Bertrand	France	1822	1900
Edward John	Routh	Angleterre	1831	1907
Al Hasan « Alhazen »	al-Haytham	Égypte	965	1039
Freeman John	Dyson	Angleterre	1923	\N
Carl Friedrich	Gauss	Allemagne	1777	1855
George	Pólya	Hongrie	1887	1985
Marcel	Bayard	France	1895	1956
Luigi	Cremona	Italie	1830	1903
Yuri	Matiyasevich	Russie	1947	\N
Bernard	Bolzano	Bohême	1781	1848
Germinal Pierre	Dandelin	Belgique	1794	1847
William	Thurston	États-Unis	1946	2012
George William	Hill	États-Unis	1838	1914
Charles	Fefferman	États-Unis	1949	\N
Julius	Plücker	Allemagne	1801	1868
Raphaël	Salem	Grèce	1898	1963
Laurent	Schwartz	France	1915	2002
Hippase de	Métaponte	Grèce	-575	-525
Stanislaw	Saks	Pologne	1897	1942
Pierre	Bouguer	France	1698	1758
Mikhail Vasilievich	Ostrogradsky	Russie	1801	1862
William Kingdon	Clifford	Angleterre	1845	1879
Irmgard	Flügge-Lotz	Allemagne	1903	1974
Paul	Painlevé	France	1863	1933
Jurij	Vega	Slovénie	1754	1802
Shing-Tung	Yau	Chine	1949	\N
Isaac	Newton	Angleterre	1643	1727
Herrmann Amandus	Schwarz	Allemagne	1843	1921
Subbayya Sivasankaranarayana	Pillai	Inde	1901	1950
Samuel	Dickstein	Pologne	1851	1939
John	Napier	Écosse	1550	1617
Michael	Stifel	Allemagne	1486	1567
John von	Neumann	Hongrie	1903	1957
Jean Johann	Bernoulli	Suisse	1667	1748
Bruno de	Finetti	Italie	1906	1985
Alfred	Loewy	Allemagne	1873	1935
Norbert	Wiener	États-Unis	1894	1964
Robert	Simson	Écosse	1687	1768
Archytas de	Tarente	Grèce	-428	-347
Anicius	Boèce	Italie	475	524
Francesco	Severi	Italie	1879	1961
Caroline	Herschel	Allemagne	1750	1848
Stephen Cole	Kleene	États-Unis	1909	1994
Henri	Cartan	France	1904	2008
Christopher	Wren	Angleterre	1632	1723
Camille	Jordan	France	1838	1922
Camille	Jordan	France	1838	1922
Louis François Antoine	Arbogast	France	1759	1803
Gertrude	Blanch	Pologne	1897	1996
Reinhard	Selten	Allemagne	1930	2016
Stanislaw Marcin	Ulam	États-Unis	1909	1984
Élie	Cartan	France	1869	1951
Moritz	Pasch	Allemagne	1843	1930
James	Gregory	Écosse	1638	1675
Ludwig	Bieberbach	Allemagne	1886	1982
Peter	Thullen	Équateur	1907	1996
Harold Scott MacDonald	Coxeter	Angleterre	1907	2003
David	Mumford	Angleterre	1937	\N
Gaston Maurice	Julia	France	1893	1978
Augustin Louis	Cauchy	France	1789	1857
Robert Daniel	Carmichael	États-Unis	1879	1967
Heinz	Hopf	Allemagne	1894	1971
Carl Gustav Jakob	Jacobi	Allemagne	1804	1851
Carl Gustav Jakob	Jacobi	Allemagne	1804	1851
Richard	Hamming	États-Unis	1915	1998
Alfred	Tarski	Pologne	1902	1983
Antoine de	Lalouvère	France	1600	1664
Hans	Freudenthal	Allemagne	1905	1990
Charles	Hermite	France	1822	1901
László	Lovász	Hongrie	1947	\N
William Rowan	Hamilton	Irlande	1805	1865
Sun	Zi	Chine	300	\N
Maxim	Kontsevich	Russie	1964	\N
André-Marie	Ampère	France	1775	1836
Maria Gaetana	Agnesi	Italie	1718	1799
Zhang	Heng	Chine	78	139
George	Green	Allemagne	1793	1841
Charlotte	Barnum	États-Unis	1860	1934
Donald	Knuth	États-Unis	1938	\N
Jordanus	Nemorarius	Allemagne	1225	1260
Maurice René	Fréchet	France	1878	1973
Ladislaus	Bortkiewicz	Pologne	1868	1931
Claude	Shannon	États-Unis	1916	2001
Charles	Ehresmann	France	1905	1979
Hipparque de	Nicée	Grèce	-190	-120
Albert	Girard	Hollande	1595	1632
Simon	Donaldson	Angleterre	1957	\N
Jakob	Nielsen	Danemark	1890	1959
Nicomède	\N	Grèce	-200	-100
Laurent	Lafforgue	France	1966	\N
Frigyes	Riesz	Hongrie	1880	1956
Autolycos de	Pitane	Grèce	-360	-300
Jean-Paul de Gua de	Malves	France	1713	1785
John	Venn	Royaume-Uni	1834	1923
Frank Plumpton	Ramsey	Angleterre	1903	1930
Kurt	Reidemeister	Allemagne	1893	1971
Hans Carl Friedrich von	Mangoldt	Allemagne	1854	1925
Daniel	Quillen	États-Unis	1940	2011
Marin	Ghetaldi	Raguse	1568	1627
Paul	Guldin	Suisse	1577	1643
Andrei Andreevich	Markov	Russie	1856	1922
Ludovico	Ferrari	Italie	1522	1565
Julius Wilhelm Richard	Dedekind	Allemagne	1831	1916
Johannes	Werner	Allemagne	1468	1528
Omar	Khayyam	Perse	1048	1123
Vladimir	Steklov	Russie	1864	1926
Adrien	Douady	France	1935	2006
Girard	Desargues	France	1591	1661
Estienne de La	Roche	France	1470	1530
Paul	Cohen	États-Unis	1934	2007
Srinivasa	Ramanujan	Inde	1887	1920
William	Emerson	Angleterre	1701	1782
Gabriel	Cramer	Suisse	1704	1752
Vladimir	Arnold	Russie	1937	2010
Al-Zarqali	\N	Espagne	1028	1087
Friedrich Wilhelm	Bessel	Allemagne	1784	1846
Zhu	Shijie	Chine	1270	1330
Guido	Castelnuovo	Italie	1865	1952
Thalès de	Milet	Grèce	-625	-547
Chen	Jingrun	Chine	1933	1996
John	Speidell	Angleterre	1600	1634
Olinde	Rodrigues	France	1794	1851
Joseph Henry Maclagan	Wedderburn	Écosse	1882	1948
Richard	Rado	Angleterre	1906	1989
Ramon	Llull	Espagne	1235	1316
Jules-Henri	Poincaré	France	1854	1912
Sophus	Lie	Norvège	1842	1899
William	Spottiswoode	Angleterre	1825	1883
Karl	Weierstrass	Allemagne	1815	1897
Pappus	d'Alexandrie	Grèce	300	400
Roger	Godement	France	1921	2016
Ernesto	Cesàro	Italie	1859	1906
Ronald	Fisher	Royaume-Uni	1962	\N
Gregori	Margulis	Russie	1946	\N
Giulio Fagnano dei	Toschi	Italie	1682	1766
Leonard Eugene	Dickson	États-Unis	1874	1954
Felix	Bernstein	Allemagne	1878	1956
Giovanni	Ceva	Italie	1648	1734
Jean le Rond	d'Alembert	France	1717	1783
Scipione del	Ferro	Italie	1465	1526
George	Boole	Angleterre	1815	1864
Saharon	Shelah	Israël	1945	\N
Christoph	Gudermann	Allemagne	1798	1852
Pafnouti Lvovitch	Tchebychev	Russie	1821	1894
Léonard « Fibonacci » de Pise 	\N	Italie	1170	1250
Marc-Antoine	Parseval	France	1755	1836
James	Cockle	Angleterre	1819	1895
Isaac	Barrow	Angleterre	1630	1677
Ménélaos	d'Alexandrie	Égypte	70	140
Charles	Babbage	Angleterre	1791	1871
Teiji	Takagi	Japon	1875	1960
Jan	Lukasiewicz	Pologne	1878	1956
John	Mair	Écosse	1467	1550
Constantin	Carathéodory	Allemagne	1873	1950
Lothar	Collatz	Allemagne	1910	1990
John	Lennard-Jones	Royaume-Uni	1894	1954
Jean-Marie	Duhamel	France	1797	1872
Petrus	Apianus	Allemagne	1495	1552
Thomas	Muir	Royaume-Uni	1844	1934
Christoff	Rudolff	Allemagne	1500	1545
Hypatie	d'Alexandrie	Égypte	370	415
Eric Temple	Bell	Écosse	1883	1960
Tibor	Radó	Hongrie	1895	1925
Yulian Vasilievich	Sokhotski	Russie	1842	1927
Pavel Sergeevich	Alexandrov	Russie	1896	1982
Richard Friederich	Arens	France	1919	2000
Hermann Günther	Grassmann	Allemagne	1809	1877
Théon	d'Alexandrie	Égypte	300	350
Condorcet	\N	France	1743	1794
Robert	Langlands	Canada	1936	\N
Marin	Mersenne	France	1588	1648
Nicolas fils	Bernoulli	Suisse	1695	1726
Abu'l-Hasan	al-Uqlidisi	Moyen-Orient	920	990
Marie-Anne-Victoire de	Prémontval	France	1724	1767
Kristen	Nygaard	Norvège	1926	2002
Oswald	Teichmüller	Allemagne	1913	1943
Euclide	\N	Grèce	-365	-275
James H.	Wilkinson	Angleterre	1919	1986
David A.	Huffman	États-Unis	1925	1999
Maurice	Bressieu	France	1546	1617
Franz	Mertens	Allemagne	1840	1927
Max	Dehn	Allemagne	1878	1952
Jean-Christophe	Yoccoz	France	1957	2016
Humphry	Ditton	Angleterre	1675	1715
Henri	Dulac	France	1870	1955
Georges	Valiron	France	1885	1955
Diophante	d'Alexandrie	Égypte de Ptolémée	214	298
Jean-Charles de	Borda	France	1733	1799
Archimède	\N	Grèce	-287	-212
Pierre	Boutroux	France	1880	1922
Friedrich Ludwig Gottlob	Frege	Allemagne	1848	1925
Saunders	MacLane	États-Unis	1909	2005
Ingrid	Daubechies	Belgique	1954	\N
Henri	Padé	France	1863	1953
Adam	Ries	Allemagne	1489	1559
Gustav	Roch	Allemagne	1839	1866
Jacques-Louis	Lions	France	1928	2001
Andreï	Kolmogorov	Russie	1903	1987
Stefan	Banach	Pologne	1892	1945
Sophie	Germain	France	1776	1831
Augustus De	Morgan	Angleterre	1806	1871
Pierre	Fatou	France	1878	1929
Gerd	Faltings	Allemagne	1954	\N
David	Hilbert	Allemagne	1862	1943
Dally Timothée Parfait	Aziegbo	Côte d'Ivoire	1988	\N
Sergueï	Sobolev	Russie	1908	1989
Jesse	Douglas	États-Unis	1897	1965
Ehrenfried Walther von	Tschirnhaus	Allemagne	1651	1708
Charles-Eugène	Delaunay	France	1816	1872
Huguette	Delavault	France	1924	2003
Farkas Wolfgang	Bolyai	Hongrie	1775	1856
James	Stirling	Écosse	1692	1770
Thomas	Abbt	Allemagne	1738	1766
Harald	Cramér	Suède	1893	1985
Bonaventura	Cavalieri	Italie	1598	1647
Gaston	Tarry	France	1843	1913
Raphaël	Bombelli	Italie	1526	1572
Benoît	Mandelbrot	États-Unis	1924	2010
Lorenzo	Mascheroni	Italie	1750	1800
René François Walter de	Sluse	Belgique	1622	1685
Zu	Chongzhi	Chine	429	500
William	Burnside	Royaume-Uni	1852	1927
Pythagore de	Samos	Grèce	-580	-500
Jules Antoine	Lissajous	France	1822	1880
Georg Joachim	Rheticus	Autriche	1514	1574
Alexander	MacAulay	Tasmanie	1863	1931
Heisuke	Hironaka	Japon	1931	\N
Lenore	Blum	États-Unis	1942	\N
Démocrite	d'Abdère	Grèce	-460	-370
Grigory	Barenblatt	Russie	1927	\N
Albert Victor	Bäcklund	Allemagne	1845	1912
Josip	Plemelj	Slovénie	1873	1967
Étienne	Bézout	France	1730	1783
Jakob	Steiner	Suisse	1796	1863
Ératosthène	\N	Grèce	-276	-196
Nobuo	Yoneda	Japon	1930	1996
Julius	Petersen	Danemark	1839	1910
Adriaan van	Roomen	Belgique	1561	1615
Paul Pierre	Lévy	France	1886	1971
Simon	Plouffe	Canada	1956	\N
Oliver	Heaviside	Angleterre	1850	1925
Gösta	Mittag-Leffler	Suède	1846	1927
Leonid	Kantorovitch	Russie	1912	1986
Étienne Louis	Malus	France	1775	1812
Vladimir	Drinfeld	Ukraine	1954	\N
Thomas	Heath	Angleterre	1861	1940
Tommaso	Ceva	Italie	1648	1737
Brahmagupta	\N	Inde	598	668
Hugo	Steinhaus	Pologne	1887	1972
Robert	Sorgenfrey	États-Unis	1915	1996
Jessie	MacWilliams	Angleterre	1917	1990
Johann Peter Gustav Lejeune	Dirichlet	Allemagne	1805	1859
Georg Ferdinand	Cantor	Allemagne	1845	1918
John H.	Conway	Angleterre	1937	\N
Günter M.	Ziegler	Allemagne	1963	\N
Pierre	Deligne	Belgique	1944	\N
Joseph-Louis de	Lagrange	Italie	1736	1813
James	Mercer	Angleterre	1883	1932
Nilakantha	Somayaji	Inde	1444	1544
Arthur Moritz	Schönflies	Allemagne	1853	1928
Hans	Zassenhaus	Allemagne	1912	1991
Carl Benjamin	Boyer	États-Unis	1906	1976
Niccolo Fontana	Tartaglia	Italie	1499	1557
Matthew	Stewart	Écosse	1717	1785
Willebrord van Roijen	Snell	Hollande	1580	1626
Gerbert	d'Aurillac	France	945	1003
Al-Biruni	\N	Perse	973	1048
Michel	Plancherel	Suisse	1885	1967
Lewis Fry	Richardson	Angleterre	1881	1953
Atle	Selberg	Norvège	1917	2007
Richard von	Mises	Autriche	1883	1953
Georg Alexander	Pick	Autriche	1859	1943
Eugenio	Beltrami	Italie	1835	1900
Emil	Artin	Autriche	1898	1962
Vladimir	Rokhlin	Russie	1919	1984
Blaise	Pascal	France	1623	1662
Julia	Robinson	États-Unis	1919	1985
Bhāskara I	\N	Inde	600	700
René	Thom	France	1923	2002
Grigori	Perelman	Russie	1966	\N
Nicolas	Bourbaki	France	1935	\N
Ménechme	\N	Grèce	-375	-325
Sergueï	Novikov	Russie	1938	\N
Emil	Post	Pologne	1897	1954
Gian-Carlo	Rota	Italie	1932	1999
Roger	Penrose	Angleterre	1931	\N
Ivar	Fredholm	Suède	1866	1927
Axel	Thue	Norvège	1863	1922
Michel	Chasles	France	1793	1880
Jacques	Aleaume	France	1562	1627
Edmund	Landau	Allemagne	1877	1938
Charles Sanders	Peirce	États-Unis	1839	1914
Louis	Bachelier	France	1870	1946
William « Student »	Gosset	Angleterre	1876	1937
Shigefumi	Mori	Japon	1951	\N
Vladimir	Voïevodski	Russie	1966	2017
Kenkichi	Iwasawa	Japon	1917	1998
Luca	Pacioli	Italie	1445	1517
Abraham Gotthelf	Kästner	Allemagne	1719	1800
Alexander	Anderson	Écosse	1582	1620
Johann	Radon	République tchèque	1887	1956
Ernst	Steinitz	Allemagne	1871	1928
John	Pell	Angleterre	1610	1685
John	Craig	Écosse	1663	1731
Thomas	Fincke	Danemark	1561	1656
George Gabriel	Stokes	Irlande	1819	1903
Grigore	Moisil	Roumanie	1906	1973
Federigo	Enriques	Italie	1871	1946
Gilles Personne de	Roberval	France	1602	1675
Jacques	Ozanam	France	1640	1717
Karol	Borsuk	Pologne	1905	1982
Alain	Connes	France	1947	\N
John	Coates	Australie	1945	\N
Ivo	Lah	Slovénie	1896	1979
Caspar	Wessel	Norvège	1745	1818
Mary Fairfax	Somerville	Royaume-Uni	1780	1872
Christian	Goldbach	Allemagne	1690	1764
Abu Ja'far Muhammad Ibn Musa	Al-Khwarizmi	Perse	780	850
Yegor Ivanovich	Zolotarev	Russie	1847	1879
François	d'Aguilon	Belgique	1566	1617
Robert	Recorde	Pays de Galles	1510	1558
Cédric	Villani	France	1973	\N
Niels Henrik	Abel	Norvège	1802	1829
Richard Ewen	Borcherds	Angleterre	1959	\N
Peter Andreas	Hansen	Danemark	1795	1874
Jean	Bourgain	Belgique	1954	\N
Johannes Müller « Regiomontanus » von	Königsberg	Allemagne	1436	1476
Paul	Erdős	Hongrie	1913	1996
Vito	Volterra	Italie	1860	1940
Abalphat	d'Ispahan	Perse	990	\N
Goro	Shimura	Japon	1930	\N
Johann	Hudde	Hollande	1630	1704
Charles de La	Faille	Hollande	1597	1652
Joseph-Alphonse	Adhémar	France	1797	1862
Thomas	Bradwardine	Angleterre	1290	1349
Piotr	Novikov	Russie	1901	1935
Luitzen Egbertus Jan	Brouwer	Hollande	1881	1966
Philolaos de	Crotone	Grèce	-470	-390
Pierre-Frédéric	Sarrus	France	1798	1861
John	Wilson	Angleterre	1741	1793
Giovanni Girolamo	Saccheri	Italie	1667	1733
Alonzo	Church	États-Unis	1903	1995
Eduard	Čech	République tchèque	1893	1960
François	Nicole	France	1683	1758
Jean Bernoulli	III	Suisse	1744	1807
Thomas Joannes	Stieltjes	Hollande	1856	1894
John Couch	Adams	Royaume-Uni	1819	1892
Charles-François	Sturm	France	1803	1855
Gregorio	Ricci-Curbastro	Italie	1853	1925
John	Tate	États-Unis	1925	\N
Arne	Beurling	Suède	1905	1986
George	Atwood	Angleterre	1746	1807
Charles Julien	Brianchon	France	1785	1864
William	Jones	Angleterre	1675	1749
Peter	Shor	États-Unis	1959	\N
Simon	Stevin	Hollande	1548	1620
Richard	Brauer	Allemagne	1901	1977
Pierre-Louis	Lions	France	1956	\N
Florimond de	Beaune	France	1601	1652
Œnopide de	Chios	Grèce	-500	-400
James	Sylvester	Angleterre	1814	1897
Ernest	Esclangon	France	1876	1954
Paul	Appell	France	1855	1930
Aleksandr Mikhailovich	Lyapunov	Russie	1857	1918
Ivan Matveevich	Vinogradov	Russie	1891	1983
Bhāskara II	\N	Inde	1114	1185
Karl Georg Christian von	Staudt	Allemagne	1798	1867
Armand	Borel	Suisse	1923	2003
Antoni	Zygmund	Pologne	1900	1992
Henri-Léon	Lebesgue	France	1875	1941
Władysław	Orlicz	Pologne	1903	1990
Eugene	Dynkin	Russie	1924	2014
Liu	Hui	Chine	200	300
Marston	Morse	États-Unis	1892	1977
William	Oughtred	Angleterre	1574	1660
Kazimierz	Zarankiewicz	Pologne	1902	1959
François	Viète	France	1540	1603
Daniel	Bernoulli	Suisse	1700	1782
W. W. Rouse	Ball	Angleterre	1850	1925
Ch'in	Chiu-Shao	Chine	1200	\N
Hassler	Whitney	États-Unis	1907	1989
Giuseppe	Vitali	Italie	1875	1932
Klaus	Roth	Allemagne	1925	2015
Vaughan	Jones	Nouvelle-Zélande	1952	\N
Qin	Jiushao	Chine	1202	1261
Cesare	Arzelà	Italie	1847	1912
Nicolaï Ivanovitch	Lobatchevsky	Russie	1792	1856
Zénodore	\N	Grèce	-200	-150
Ivan	Vidav	Slovénie	1918	2015
Sheila Scott	Macintyre	Écosse	1910	1960
Pelageya	Polubarinova-Kochina	Russie	1899	1999
Jean Dominique	Cassini	France	1625	1712
John Theophilus	Desaguliers	Angleterre	1683	1744
Rolf	Nevanlinna	Finlande	1895	1980
Louis	Poinsot	France	1777	1859
Aristote	\N	Grèce	-384	-322
Danilo	Blanuša	Croatie	1903	1987
Erich	Kähler	Allemagne	1905	2000
Bernhard	Riemann	Allemagne	1826	1866
Andreï Nikolaïevitch	Tikhonov	Russie	1906	1993
John Edensor	Littlewood	Angleterre	1885	1977
Adrien-Marie	Legendre	France	1752	1833
Émile	Borel	France	1871	1956
Claude	Perrault	France	1613	1688
Roy	Kerr	Nouvelle-Zélande	1934	\N
Ferdinand Georg	Frobenius	Allemagne	1849	1917
Adolf	Hurwitz	Allemagne	1859	1919
Ahmès	\N	Égypte	-1700	-1600
Jacques Philippe Marie	Binet	France	1786	1856
Henry John Stephen	Smith	Angleterre	1826	1883
Claude-Gaspard Bachet de	Méziriac	France	1581	1638
Charles	Méray	France	1835	1911
Dioclès	\N	Grèce	-200	-150
Jean-Pierre	Serre	France	1926	\N
Édouard	Lucas	France	1842	1891
William	Feller	Croatie	1906	1970
Harald	Bohr	Danemark	1887	1951
Frans van	Schooten	Hollande	1615	1660
Kunihiko	Kodaira	Japon	1915	1997
Georg	Mohr	Danemark	1640	1697
Max	Zorn	Allemagne	1906	1993
Charles	Pisot	France	1910	1984
William Timothy	Gowers	Angleterre	1963	\N
Abraham Adolf	Fraenkel	Allemagne	1891	1965
Carl Gustav Axel	Harnack	Allemagne	1851	1888
Carl	Runge	Allemagne	1856	1927
Émilie du	Châtelet	France	1706	1749
Eudoxe de	Cnide	Grèce	-408	-347
Elwin Bruno	Christoffel	Allemagne	1829	1900
Pietro Antonio	Cataldi	Italie	1548	1626
Aguilon	\N	Belgique	1566	1617
Zygmunt	Janiszewski	Pologne	1888	1920
John Griggs	Thompson	États-Unis	1932	\N
Arthur	Wieferich	Allemagne	1884	1954
Zénon	d'Elée	Grèce	-490	-430
Issai	Schur	Russie	1875	1941
Sergeï Natanovitch	Bernstein	Ukraine	1880	1968
Haïm	Brezis	France	1944	\N
Oronce	Fine	France	1494	1555
Pavel Samuilovich	Urysohn	Russie	1898	1924
Bertrand	Russell	Angleterre	1872	1970
Alphonse de	Polignac	France	1817	1890
John	Wallis	Angleterre	1616	1703
Héron	d'Alexandrie	Égypte	50	100
Edmond	Laguerre	France	1834	1886
Lars Valerian	Ahlfors	Finlande	1907	1996
Alexander Markovich	Ostrowski	Russie	1893	1986
Bartel Leendert van der	Waerden	Hollande	1903	1996
Henri Auguste	Delannoy	France	1833	1915
Ruđer Josip	Bošković	Raguse	1711	1787
Abraham	Robinson	États-Unis	1918	1974
Andrei	Okounkov	Russie	1969	\N
Shiing-Shen	Chern	Chine	1911	2004
Nicolas neveu	Bernoulli	Suisse	1687	1759
Norman	Levinson	États-Unis	1912	1975
Lotfi	Zadeh	Azerbaïdjan	1921	2017
Gottfried Wilhelm	Leibniz	Allemagne	1646	1716
Abraham ibn	Ezra	Espagne	1090	1167
Hippias	d'Élis	Grèce	-460	\N
Paul	Halmos	Hongrie	1916	2006
Witold	Hurewicz	Pologne	1904	1956
Joseph Diaz	Gergonne	France	1771	1859
Jon	Barwise	États-Unis	1942	2000
Giuseppe	Peano	Italie	1858	1932
Ernst Leonard	Lindelöf	Finlande	1870	1946
Jean-Marc	Fontaine	France	1944	\N
Muhammad	Aboûl-Wafâ	Perse	940	998
Arthur	Cayley	Angleterre	1821	1895
Edward	Marczewski	Pologne	1907	1976
François Le	Lionnais	France	1901	1984
Heinrich	Weber	Allemagne	1842	1913
Piero della	Francesca	Italie	1416	1492
Mikhail	Lavrentyev	Russie	1900	1980
Carlo Emilio	Bonferroni	Italie	1892	1960
Thomas	Harriot	Angleterre	1560	1621
Leone Battista	Alberti	Italie	1404	1472
Eugène Charles	Catalan	Belgique	1814	1894
Curtis T.	McMullen	États-Unis	1958	\N
William	Brouncker	Angleterre	1620	1684
Hermann Klaus Hugo	Weyl	Allemagne	1885	1955
Andrew	Wiles	Angleterre	1953	\N
Tsuneo	Tamagawa	Japon	1925	\N
John Forbes	Nash	États-Unis	1928	2015
Johannes	Widman	Allemagne	1462	1498
Josef	Wronski	Pologne	1778	1853
Otto	Toeplitz	Allemagne	1881	1940
Georges de	Rham	Suisse	1903	1990
Yehoshua	Bar-Hillel	Israël	1915	1975
Anthemius de	Tralles	Byzance	474	534
Vincenzo	Viviani	Italie	1622	1703
Terence	Tao	Australie	1975	\N
Juliusz	Schauder	Pologne	1899	1943
Jacques	Tits	Belgique	1930	\N
Aristarque de	Samos	Grèce	-310	-230
Gaston	Darboux	France	1842	1917
James	Ivory	Écosse	1765	1842
John	d'Hollywood	Angleterre	1200	1256
Peter	Lax	États-Unis	1926	\N
Stephen	Smale	États-Unis	1930	\N
Alan	Baker	Angleterre	1939	\N
Thomas	Simpson	Angleterre	1710	1761
Christian	Huygens	Hollande	1629	1695
\.

COMMIT;