
--
-- PostgreSQL database dump
-- Inspired from https://fr.wikipedia.org/wiki/Projet:Math%C3%A9matiques/Liste_des_math%C3%A9maticiens
--

\set AUTOCOMMIT off
\set ON_ERROR_ROLLBACK on

SET client_encoding = 'UTF8';

DROP TABLE public.mathematicians;
CREATE TABLE public.mathematicians (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname varchar(255) NOT NULL,
  lastname varchar(255),
  country varchar(255),
  birth smallint,
  death smallint
);

COPY public.mathematicians (firstname, lastname, country, birth, death) FROM stdin;
Abalphat	d'Ispahan	Perse	990	\N
Abraham Adolf	Fraenkel	Allemagne	1891	1965
Alexander Markovich	Ostrowski	Russie	1893	1986
\.
